#!/usr/bin/env bash
: "${WATCH_INTERVAL:=10}" "${BASELINE_SECONDS:=60}" "${BACKEND_UNREADY_SECONDS:=30}"
: "${COLLECTION_FAILURE_SECONDS:=60}" "${HTTP_FAILURE_RATIO:=0.01}" "${HTTP_FAILURE_SUSTAIN_SECONDS:=60}"
: "${HTTP_WINDOW_SECONDS:=60}" "${EXECUTOR_CPU_PERCENT:=95}" "${EXECUTOR_CPU_SUSTAIN_SECONDS:=60}"
: "${EXECUTOR_AVAILABLE_MEMORY_PERCENT:=10}" "${EXECUTOR_FREE_DISK_GIB:=2}"
: "${HPA_SATURATION_SECONDS:=60}" "${REQUIRED_BACKEND_READY:=2}" "${WATCH_DB:=1}"
: "${NAMESPACE:=app}" "${DATA_NAMESPACE:=data}" "${MONITORING_NAMESPACE:=monitoring}" "${BACKEND_NAME:=backend}"
: "${DB_NAMESPACE:=data}" "${DB_CLUSTER:=ticketing-postgresql}" "${DB_NAME:=ticketing}" "${DB_USER:=postgres}" "${DB_CONTAINER:=postgres}"
: "${STOP_GRACE_SECONDS:=30}" "${REQUIRE_PLAN_METRICS:=1}"
for name in WATCH_INTERVAL BASELINE_SECONDS BACKEND_UNREADY_SECONDS COLLECTION_FAILURE_SECONDS HTTP_FAILURE_SUSTAIN_SECONDS HTTP_WINDOW_SECONDS EXECUTOR_CPU_SUSTAIN_SECONDS HPA_SATURATION_SECONDS REQUIRED_BACKEND_READY STOP_GRACE_SECONDS; do
  [[ ${!name} =~ ^[0-9]+$ ]] || { echo "$name: 정수가 필요합니다" >&2; return 2; }
done
((WATCH_INTERVAL>0 && HTTP_WINDOW_SECONDS>0 && HTTP_WINDOW_SECONDS<=60 && REQUIRED_BACKEND_READY>0 && STOP_GRACE_SECONDS>0)) || return 2
for name in HTTP_FAILURE_RATIO EXECUTOR_CPU_PERCENT EXECUTOR_AVAILABLE_MEMORY_PERCENT EXECUTOR_FREE_DISK_GIB; do
  [[ ${!name} =~ ^[0-9]+([.][0-9]+)?$ ]] || { echo "$name: 0 이상의 숫자가 필요합니다" >&2; return 2; }
done
[[ $WATCH_DB =~ ^[01]$ && $REQUIRE_PLAN_METRICS =~ ^[01]$ ]] || return 2
jq -en --argjson ratio "$HTTP_FAILURE_RATIO" --argjson cpu "$EXECUTOR_CPU_PERCENT" --argjson mem "$EXECUTOR_AVAILABLE_MEMORY_PERCENT" '$ratio<=1 and $cpu<=100 and $mem<=100' >/dev/null || return 2
for label in "$NAMESPACE" "$DATA_NAMESPACE" "$MONITORING_NAMESPACE" "$BACKEND_NAME"; do
  [[ $label =~ ^[a-zA-Z0-9_.-]+$ ]] || return 2
done
