#!/usr/bin/env bash

set -uo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
repo_root="$(CDPATH= cd -- "${script_dir}/../.." && pwd)"

ssh_user="${SSH_USER:-root}"
ssh_key_path="${SSH_KEY_PATH:-${HOME}/.ssh/ticketing_infra_ed25519}"
inventory_file="${INVENTORY_FILE:-${repo_root}/ansible/cluster/inventory.ini}"

declare -A host_ip=(
  [lb1]="10.1.93.60"
  [lb2]="10.1.93.61"
  [m1]="10.1.93.62"
  [m2]="10.1.93.63"
  [m3]="10.1.93.64"
  [w1]="10.1.93.66"
  [w2]="10.1.93.67"
  [w3]="10.1.93.68"
  [w4]="10.1.93.110"
  [w5]="10.1.93.111"
  [w6]="10.1.93.112"
  [ansible-controller]="10.1.93.115"
)

declare -A host_group=(
  [lb1]="lb"
  [lb2]="lb"
  [m1]="masters"
  [m2]="masters"
  [m3]="masters"
  [w1]="workers"
  [w2]="workers"
  [w3]="workers"
  [w4]="data_workers"
  [w5]="data_workers"
  [w6]="data_workers"
  [ansible-controller]="operations"
)

for command_name in ssh ssh-keygen ssh-copy-id sshpass; do
  command -v "${command_name}" >/dev/null 2>&1 || {
    printf '필수 명령을 찾을 수 없습니다: %s\n' "${command_name}" >&2
    exit 1
  }
done

if [[ ! -f "${ssh_key_path}" ]]; then
  install -d -m 0700 "$(dirname -- "${ssh_key_path}")"
  ssh-keygen \
    -t ed25519 \
    -f "${ssh_key_path}" \
    -N "" \
    -C "ticket-rail-automation" \
    -q
fi

printf '초기 SSH 비밀번호: '
read -rs ssh_password
printf '\n'
export SSHPASS="${ssh_password}"
unset ssh_password

declare -A verified=()

while IFS= read -r host_name; do
  ip="${host_ip[${host_name}]}"
  printf '%-20s %-15s ' "${host_name}" "${ip}"

  if sshpass -e ssh-copy-id \
      -o StrictHostKeyChecking=accept-new \
      -o ConnectTimeout=5 \
      -i "${ssh_key_path}.pub" \
      "${ssh_user}@${ip}" >/dev/null 2>&1 \
    && ssh \
      -i "${ssh_key_path}" \
      -o BatchMode=yes \
      -o ConnectTimeout=5 \
      -o StrictHostKeyChecking=accept-new \
      "${ssh_user}@${ip}" true >/dev/null 2>&1; then
    verified["${host_name}"]=1
    printf 'OK\n'
  else
    printf 'FAILED\n'
  fi
done < <(printf '%s\n' "${!host_ip[@]}" | sort)

unset SSHPASS
install -d -m 0755 "$(dirname -- "${inventory_file}")"

{
  printf '# Generated by scripts/setup/deploy-ssh-keys.sh\n\n'

  for group_name in lb masters workers data_workers operations; do
    printf '[%s]\n' "${group_name}"
    while IFS= read -r host_name; do
      [[ "${host_group[${host_name}]}" == "${group_name}" ]] || continue
      [[ -n "${verified[${host_name}]:-}" ]] || continue
      printf '%s ansible_host=%s\n' "${host_name}" "${host_ip[${host_name}]}"
    done < <(printf '%s\n' "${!host_ip[@]}" | sort)
    printf '\n'
  done

  cat <<EOF
[k8s:children]
masters
workers
data_workers

[all:vars]
ansible_user=${ssh_user}
ansible_ssh_private_key_file=${ssh_key_path}
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
EOF
} > "${inventory_file}"

printf 'Inventory written: %s\n' "${inventory_file}"
printf 'Verify with: ansible all -i %q -m ping\n' "${inventory_file}"
