apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-nammer-store-prod
  namespace: app
spec:
  secretName: api-nammer-store-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.nammer.store
