---
- name: Install MetalLB
  hosts: masters
  become: true
  gather_facts: false

  tasks:

    - name: Install MetalLB
      ansible.builtin.command:
        cmd: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.15.3/config/manifests/metallb-native.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      changed_when: true
